title: Jean Bedel GNAMIEN
author: Jean Bedel GNAMIEN
email: "jean.gnamien@master.centralelille.fr"
url: https://jeangnamien.github.io # root address of the site
description: >
  Engineering student pursuing Masterâ€™s in Data Science. Portfolio showcasing projects, internships, and skills in software development, AI, and data analysis.

permalink: /:slug

favicon: "./logo.png" # relative path to your favicon

twitter:
  username: jeangnamien
  card: summary_large_image

# GitHub and LinkedIn links can be included in _data/home.yml or directly in templates if needed

remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark"       # can be "light", "dark" or "auto"
  appearance_toggle: true
  back_home_text: "home.."
  date_format: "%Y-%m-%d"
  show_description: true
  show_navbar: true
  show_footer: true
  show_copyright: true
  show_projects: true
  show_blog: true
  show_old_projects: true
  show_misc_list: true
  show_reading_time: true
  show_tags: true

  home:
    title_projects: Portfolio
    title_misc_list: Details
    title_blog: Blog
    title_old_projects: Past Projects

soopr:
  publish_token: "" # optional: sign up at https://www.soopr.co

highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
