title: "Jean GNAMIEN"
name: "Jean Bedel Bekanfa GNAMIEN"
email: "jean.gnamien@master.centralelille.fr"
description: "Data Science & Engineering Student — École Centrale Lille & École Centrale Casablanca."

baseurl: ""
url: "https://jeangnamien.github.io"

github_username: "jeangnamien"
linkedin_username: "jean-bedel-gnamien"

cv_link: "https://github.com/jeangnamien/Lab/raw/master/CV.pdf"
business_card: "https://github.com/jeangnamien/Lab/releases/latest/download/card.pdf"

theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.22.0"
minimal_mistakes_skin: "neon"

locale: 'en-US'

# Author profile
author:
  name: "Jean GNAMIEN"
  avatar: "/assets/images/profile.jpg"
  bio: "Data Science & Engineering Student — Centrale Lille & Centrale Casablanca"
  location: "Lille, France"
  email: "jean.gnamien@master.centralelille.fr"
  github: "jeangnamien"

# Footer logos & links
footer:
  links:
    - label: 'GitHub'
      icon: 'fab fa-fw fa-github'
      url: 'https://github.com/jeangnamien'
    - label: 'LinkedIn'
      icon: 'fab fa-fw fa-linkedin'
      url: 'https://www.linkedin.com/in/jean-bedel-bekanfa-gnamien-bb21aa305'

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Skin dark
#minimal_mistakes_skin : 'dark'

# Permalink
permalink: /:categories/:title/
